# Generated by Django 5.0.4 on 2024-05-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название клуба')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс клуба')),
                ('contacts_phone', models.CharField(max_length=20, verbose_name='Контактный номер')),
                ('contacts_instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на инсту')),
                ('contacts_telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на телегу')),
                ('map_link', models.URLField(verbose_name='Ссылка на карту')),
                ('map_lat', models.FloatField(verbose_name='Долгота на карте')),
                ('map_lng', models.FloatField(verbose_name='Широта на карте')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='PCLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уровень компьютера',
                'verbose_name_plural': 'Уровни компьютера',
            },
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bonus_balance',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Балланс бонусов'),
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Номер компьютера')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.club', verbose_name='Клуб')),
                ('pc_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pclevel', verbose_name='Тип компьютера')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
