# Generated by Django 5.0.4 on 2024-05-16 07:29

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_club_pclevel_alter_appuser_options_appuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.avatar_file_name, verbose_name='Аватарка'),
        ),
    ]
